[tool.poetry]
name = "roddy-g_brain_games"
version = "0.1.1"
description = ""
authors = ["Roddy <per677199@yandex.ru>"]

packages = [
  { include = "brain_games" },
]
[tool.poetry.dependencies]
python = "^3.8"
prompt = "^0.4.1"

[tool.poetry.dev-dependencies]
flake8 = "^3.8.3"

[tool.poetry.scripts]
brain-games = "brain_games.scripts.brain_games:main"
brain-even = "brain_games.scripts.brain-even:main"
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"


